export const emailPattern = /^[a-z0-9+._-]+@[a-z0-9+.-]+\.[a-z]{2,4}$/;

export const COLORS = {
  primaryText: 'rgb(242, 101, 57)',
  primaryBackground: 'rgb(242, 101, 57)',
};

export const randomColor = [
  'magenta',
  'red',
  'volcano',
  'orange',
  'gold',
  'lime',
  'green',
  'cyan',
  'blue',
  'geekblue',
  'purple',
];

export const CURRENCY_LIST = [
  { value: 'USD', label: 'USD | US Dollar' },
  { value: 'EUR', label: 'EUR | Euro' },
  { value: 'GBP', label: 'GBP | British Pound' },
  { value: 'JPY', label: 'JPY | Japanese Yen' },
  { value: 'AUD', label: 'AUD | Australian Dollar' },
  { value: 'CAD', label: 'CAD | Canadian Dollar' },
  { value: 'INR', label: 'INR | Indian Rupee' },
  { value: 'CNY', label: 'CNY | Chinese Yuan' },
  { value: 'BRL', label: 'BRL | Brazilian Real' },
  { value: 'MXN', label: 'MXN | Mexican Peso' },
  { value: 'SGD', label: 'SGD | Singapore Dollar' },
  { value: 'NZD', label: 'NZD | New Zealand Dollar' },
  { value: 'CHF', label: 'CHF | Swiss Franc' },
  { value: 'HKD', label: 'HKD | Hong Kong Dollar' },
  { value: 'SEK', label: 'SEK | Swedish Krona' },
  { value: 'NOK', label: 'NOK | Norwegian Krone' },
  { value: 'DKK', label: 'DKK | Danish Krone' },
  { value: 'ZAR', label: 'ZAR | South African Rand' },
  { value: 'KRW', label: 'KRW | South Korean Won' },
  { value: 'THB', label: 'THB | Thai Baht' },
  { value: 'RUB', label: 'RUB | Russian Ruble' },
  { value: 'PLN', label: 'PLN | Polish Zloty' },
  { value: 'TRY', label: 'TRY | Turkish Lira' },
  { value: 'AED', label: 'AED | UAE Dirham' },
  { value: 'SAR', label: 'SAR | Saudi Riyal' },
  { value: 'MYR', label: 'MYR | Malaysian Ringgit' },
  { value: 'IDR', label: 'IDR | Indonesian Rupiah' },
  { value: 'PHP', label: 'PHP | Philippine Peso' },
  { value: 'VND', label: 'VND | Vietnamese Dong' },
  { value: 'NGN', label: 'NGN | Nigerian Naira' },
  { value: 'EGP', label: 'EGP | Egyptian Pound' },
  { value: 'ARS', label: 'ARS | Argentine Peso' },
  { value: 'CLP', label: 'CLP | Chilean Peso' },
  { value: 'COP', label: 'COP | Colombian Peso' },
  { value: 'PEN', label: 'PEN | Peruvian Sol' },
  { value: 'UYU', label: 'UYU | Uruguayan Peso' },
  { value: 'BGN', label: 'BGN | Bulgarian Lev' },
  { value: 'HRK', label: 'HRK | Croatian Kuna' },
  { value: 'HUF', label: 'HUF | Hungarian Forint' },
  { value: 'RON', label: 'RON | Romanian Leu' },
  { value: 'CZK', label: 'CZK | Czech Koruna' },
  { value: 'ISK', label: 'ISK | Icelandic Krona' },
  { value: 'KZT', label: 'KZT | Kazakhstani Tenge' },
  { value: 'UAH', label: 'UAH | Ukrainian Hryvnia' },
  { value: 'BHD', label: 'BHD | Bahraini Dinar' },
  { value: 'KWD', label: 'KWD | Kuwaiti Dinar' },
  { value: 'OMR', label: 'OMR | Omani Rial' },
  { value: 'JOD', label: 'JOD | Jordanian Dinar' },
  { value: 'LYD', label: 'LYD | Libyan Dinar' },
  { value: 'MAD', label: 'MAD | Moroccan Dirham' },
  { value: 'PKR', label: 'PKR | Pakistani Rupee' },
  { value: 'BDT', label: 'BDT | Bangladeshi Taka' },
];

export const COUNTRY_LIST = [
  { value: 'GB', label: 'United Kingdom' },
  { value: 'DE', label: 'Germany' },
  { value: 'US', label: 'United States' },
  { value: 'AT', label: 'Austria' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DK', label: 'Denmark' },
  { value: 'EE', label: 'Estonia' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GR', label: 'Greece' },
  { value: 'HR', label: 'Croatia' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IT', label: 'Italy' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MT', label: 'Malta' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RO', label: 'Romania' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'ES', label: 'Spain' },
  { value: 'SE', label: 'Sweden' },
  { value: 'AU', label: 'Australia' },
  { value: 'CA', label: 'Canada' },
  { value: 'JP', label: 'Japan' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'NO', label: 'Norway' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'SG', label: 'Singapore' },
  { value: 'BR', label: 'Brazil' },
  { value: 'CH', label: 'Switzerland' },
];

export const LANG_LIST = [
  { value: 'eng', label: 'English' },
];

export const CAMPAIGN_STATUS = {
  CAMPAIGN: 'screen',
  GEO_LOCATION: 'catalogs',
  VENUE_TYPES: 'timings',
  TIME: 'media',
  GALLERY: 'review',
};
